# Generated by Django 3.2.3 on 2021-07-08 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FileName', models.CharField(max_length=255)),
                ('FilePath', models.FilePathField(path='G:\\django_projects\\git_satyam_adf\\AutoDocumentFiling\\adf_main\\media')),
                ('Content_HTML', models.TextField()),
                ('Content_TEXT', models.TextField()),
                ('Page_no', models.IntegerField()),
            ],
        ),
    ]
